Update 123_WPO_dual_class.tpa
Otherwise It won't copy properly 'clabma01.2da' to override and the component [SBO - Stat-based Bonus Spells] will get the error: 
"ERROR locating resource for 'APPEND'
Resource [CLABMA02.2DA] not found in KEY file:
	[./chitin.key]
Stopping installation because of error.
ERROR: [kitlist.2da] -> [override/kitlist.2da] Patching Failed (COPY) (Failure("resource [CLABMA02.2DA] not found for 'APPEND'"))
Stopping installation because of error.
Stopping installation because of error.
"

Changing "ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA01.2da~" -> "ELSE" Solves the problem during the installation.